### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by KshitijKarthick** [alendit/sphinx-pyreverse#1]
### Import Error
- Ran pip2 install -e git+https://github.com/alendit/sphinx-pyreverse.git#egg=sphinx-pyreverse.py
- Added     'sphinx_pyreverse' in extensions at conf.py

`ImportError: No module named 
/run/media/kshitijkarthick/LinuxData/Programming/FinalProject/sphinx_pyreverse/sphinx_pyreverse.py
1
`

Log File Generated [sphinx-err-oZPxSf.log.txt](https://github.com/alendit/sphinx-pyreverse/files/231163/sphinx-err-oZPxSf.log.txt)

**Comment by katsar0v** [comment]
> Traceback (most recent call last):
>   File "/home/katsarov/pypy/bin/pyreverse", line 11, in <module>
>     sys.exit(run_pyreverse())
>   File "/home/katsarov/pypy/site-packages/pylint/__init__.py", line 35, in run_pyreverse
>     Run(sys.argv[1:])
>   File "/home/katsarov/pypy/site-packages/pylint/pyreverse/main.py", line 115, in __init__
>     sys.exit(self.run(args))
>   File "/home/katsarov/pypy/site-packages/pylint/pyreverse/main.py", line 127, in run
>     black_list=self.config.black_list)
>   File "/home/katsarov/pypy/site-packages/pylint/pyreverse/inspector.py", line 340, in project_from_files
>     fpath = modutils.file_from_modpath(something.split('.'))
>   File "/home/katsarov/pypy/site-packages/astroid/modutils.py", line 324, in file_from_modpath
>     return file_info_from_modpath(modpath, path, context_file)[0]
>   File "/home/katsarov/pypy/site-packages/astroid/modutils.py", line 369, in file_info_from_modpath
>     return _file_from_modpath(modpath, path, context)
>   File "/home/katsarov/pypy/site-packages/astroid/modutils.py", line 582, in _file_from_modpath
>     mtype, mp_filename = _module_file(modpath, path)
>   File "/home/katsarov/pypy/site-packages/astroid/modutils.py", line 673, in _module_file
>     return _search_zip(modpath, pic)[:2]
>   File "/home/katsarov/pypy/site-packages/astroid/modutils.py", line 606, in _search_zip
>     raise ImportError('No module named %s' % '.'.join(modpath))
> ImportError: No module named app


I got a similar error

**Comment by doublethefish** [comment]
You should now be able to run 'pip install sphinx-pyreverse' against python2 and python3, on sphinx 2.2.0
