### ISSUE TITLE
Thank you for this project's code clarity

### ISSUE THREAD

**Issue by myselfhimself** [alendit/sphinx-pyreverse#16]
Hello,
I have got a lot of inspiration from your code for writing this other sphinx extension lately: https://github.com/myselfhimself/gmic-sphinx/
It helped me read less the not-so-easy to understand Sphinx extension-writing documentation.
Thank you for the quality of your work!
Best regards

**Comment by alendit** [comment]
Thanks, but A LOT of credit goes to @doublethefish!

**Comment by doublethefish** [comment]
Awww shucks :) But I used @alendit 's original to learn the same things.

@myselfhimself your stuff looks fun, I am really glad to see someone doing stuff with g'mic again.

**Comment by myselfhimself** [comment]
:)) happy to see this escalation of thankfulness :)
g'mic is still in development with a new version every 1-2 months or so,
and I work a few meters away from its creator :)
I hope to see it revived in Blender 3d namely. Have a nice day and keep up
the good programming work

čt 27. 8. 2020 v 20:37 odesílatel Frank Harrison <notifications@github.com>
napsal:

**Comment by myselfhimself** [comment]
Hey
just a quick question, maybe you could help me :)
I would like to generate a figure with a caption
what should the code be ?
`node.figure(uri="myurl", content="my caption")` ?
in HTML nothing gets shown apart from a figure div with no content..
I cannot find the proper API for this...
[Here is the related language syntax](https://docutils.sourceforge.io/docs/ref/rst/directives.html#figure)

**Comment by alendit** [comment]
Not sure, I'd try `node.figure(uri="myurl", alt="my caption")`

**Comment by myselfhimself** [comment]
@alendit, thanks for guessing with me!
I ended up with the following:
```python
        figure = nodes.figure()
        img = nodes.image(uri=output_filename)
        caption = nodes.caption(text=original_command)
        figure += img      
        figure += caption

```
which yields a caption with a permalink even:
```html
<div class="figure align-default" id="id1">
<img alt="_images/4a2a881c-eb87-11ea-9e0e-8cec4b8c0881.png" src="_images/4a2a881c-eb87-11ea-9e0e-8cec4b8c0881.png">
<p class="caption"><span class="caption-text">sp leno blur 4</span><a class="headerlink" href="#id1" title="Permalink to this image">¶</a></p>
</div>
```

:)
