### ISSUE TITLE
Why is this extension not parallel safe?

### ISSUE THREAD

**Issue by thedrow** [alendit/sphinx-pyreverse#18]
This extension to the best of my knowledge should be parallel safe and therefore must be marked as one so that we can use `-jauto` when generating docs.

**Comment by doublethefish** [comment]
Feel free to raise a PR if you believe so. I do not know what -jauto is or does or how to ensure we can test it properly.

**Comment by thedrow** [comment]
Can two instances of pyreverse run in parallel? The answer is yes according to the code unless I'm missing something.

sphinx-build can run in parallel to build the documentation faster. However if an extension does not mark itself as parallel-safe, it forces a serial run despite the fact that you specified `-j 2` or `-j auto`.
