### ISSUE TITLE
`pyreverse` fails with "module cannot be found" Exceptions

### ISSUE THREAD

**Issue by Nic30** [alendit/sphinx-pyreverse#25]
Hello,

I think that this project does not work for modules which do have more than 3 levels of hierarchy, because PYTHONPATH or CWD are not set correctly for pyreverse.

https://readthedocs.org/projects/hdlconvertorast/builds/13513547/

**Comment by Nic30** [comment]
duplicit

**Comment by doublethefish** [comment]
Fixed by fedd84e076c7.

As per the commit message the RCA showed that `astroid` caused the issue. More info on that bug: https://github.com/PyCQA/astroid/issues/930

In short `pyreverse` fails to determine if a module is relative to another when generating the diagrams.

Marking as closed.
