### ISSUE TITLE
html build missing 'uml_images' directory and invalid generated graph image url

### ISSUE THREAD

**Issue by fskoras** [alendit/sphinx-pyreverse#30]
After html docs generatorin the 'uml_images' directory is not present in build/html output and the image path is incorrect:
![invalid_img_path](https://user-images.githubusercontent.com/22472554/124266296-1233c900-db37-11eb-9339-5ce89dd8b440.png)

Python packages installed:
Package                       Version
----------------------------- ------------
alabaster                     0.7.12
astroid                       2.6.2
Babel                         2.9.1
certifi                       2021.5.30
chardet                       4.0.0
checksumdir                   1.2.0
cmake                         3.20.3
colorama                      0.4.4
cycler                        0.10.0
deepdiff                      5.5.0
docutils                      0.16
graphviz                      0.16
idna                          2.10
imagesize                     1.2.0
isort                         5.8.0
Jinja2                        3.0.1
kiwisolver                    1.3.1
lazy-object-proxy             1.6.0
MarkupSafe                    2.0.1
matplotlib                    3.4.2
mccabe                        0.6.1
ninja                         1.10.0.post2
numpy                         1.20.3
ordered-set                   4.0.2
packaging                     20.9
Pillow                        8.2.0
pip                           20.2.3
prompt-toolkit                3.0.19
Pygments                      2.9.0
pylint                        2.8.3
pyparsing                     2.4.7
python-dateutil               2.8.1
pytz                          2021.1
requests                      2.25.1
setuptools                    49.2.1
six                           1.16.0
snowballstemmer               2.1.0
Sphinx                        4.0.2
sphinx-pyreverse              0.0.17
sphinx-rtd-theme              0.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
toml                          0.10.2
urllib3                       1.26.5
wcwidth                       0.2.5
wrapt                         1.12.1

**Comment by theavey** [comment]
Are you on Windows? I am thinking that's the issue because I am seeing similar behaviors on Windows.

**Comment by doublethefish** [comment]
Please add a decent repro case and/or unittest, and then reopen this issue :)
