### ISSUE TITLE
I do not understand how to use sphinx-pyreverse

### ISSUE THREAD

**Issue by simarocchi** [alendit/sphinx-pyreverse#31]
Please can you send a detailed walkthrough for a very simple case ?

Thank you so much for any help,
Simone

**Comment by doublethefish** [comment]
It sounds like you're not familiar with Sphinx as this is a plug-in that is installed in the normal way (adding the plug-in to your `extensions = ["sphinx_pyreverse",]` list in your sphinx `conf.py`.

Note that you do have to have sphinx installed and working already. *Then* you install this plug-in.

Once you have sphinx configured, just add the following to one of your `.rst` files.

```
.. uml:: my package.class
   :classes:
```

For example, read the following example of setting up a sphinx project; I've deep-linked you to the section on adding a table of contents, which is exactly the same principle:
https://pythonhosted.org/an_example_pypi_project/sphinx.html#table-of-contents

Feel free to edit the following section in the README if it's not good enough.
https://github.com/alendit/sphinx-pyreverse#usage
