### ISSUE TITLE
pyreverse tool is hardcoded

### ISSUE THREAD

**Issue by AlbertMietus** [alendit/sphinx-pyreverse#5]
Currently, the "path" to **pyreverse** is hardcode. Or more exact: the is not path. It just assumes the (correct) tools in the path ...
This isn't a great idea for supporting multiple version, systems etc.

The same applies to other details too; this is the most important one. 
Others are: fig-extension/type (``-o``), name (``-p``), scale, ``DIR_NAME``, ...

Plz, make sphinx-pyreverse  configurable, from conf.py

Thanks

_Note: I would like to use this (or similar) extension. However it has some issues. I  will report them one-by-one._

**Comment by doublethefish** [comment]
Fixed by #15
