### ISSUE TITLE
Code readability (is it maintained)

### ISSUE THREAD

**Issue by AlbertMietus** [alendit/sphinx-pyreverse#6]
The current code-base feels a bit "old". 

I think it would be nice to update is to current "python3" style/standards (even when it work, it is not clear it does allow python 2 and 3)

Some examples
* _Line 2_: **date 2012** ...
* _Line 52_:  The **call to the tool** is "hidden" in a print statement. At least I could find it initially
* _Line 20/25_:  **IPython debug code**  (as comment)
* _Line 15/18, 76/80_ : (**PIL** use/support) yeah ... nice
* _Line 52,67_: ``generate_img`` The function suggest ... But the work is done in the/another spot 

This raises the main question: is this extension still supported? Or should I search for another of engineer one myself? _(Or, can I help)_

Thanks for updating and so answering my question 
 
_Note: I would like to use this (or similar) extension. However it has some issues. I  will report them one-by-one._

**Comment by doublethefish** [comment]
We have updated the code to modern syntax, testing and linting standards.
