### ISSUE TITLE
Log/Tracing/Errors output is missing

### ISSUE THREAD

**Issue by AlbertMietus** [alendit/sphinx-pyreverse#7]
The current code has no/limited _"tracking"_ build in. So, when it doesn't work, it just doesn't ...
without any hints/feedback on missing config/path/other "thinks"

Plz, add a few print/log statement when this go wrong. So the user (me) has a clue why it doesn't work as expected

Thanks

_Note: I would like to use this (or similar) extension. However it has some issues. I will report them one-by-one._

**Comment by doublethefish** [comment]
We now log out errors from pyreverse to stdout
