### ISSUE TITLE
The Directive class has moved

### ISSUE THREAD

**Issue by Carelvd** [alendit/sphinx-pyreverse#8]
Hi,

In case you are not aware of this just yet, the `Directive` class has moved from `sphinx.util.compat` to `docutils.parsers.rst`. To accommodate this one must modify the `sphinx_pyreverse/__init__.py` file at line 11 as follows

`from docutils.parsers.rst import Directive`

Also your `setup.py` file does not have a dependency upon `Pylint`. To remedy this modify line 25 as follows 

`      install_requires=['sphinx', 'docutils', 'pylint'],`

I have attached a patch wrapped into a zip file (Github won't let me include a vanilla patch file). This is my first patch, hence the verbose descriptions above.

[Directive and Pylint Patch.zip](https://github.com/alendit/sphinx-pyreverse/files/1119250/Directive.and.Pylint.Patch.zip)

**Comment by doublethefish** [comment]
This was fixed by PR #10
